# Start from node base image
FROM node:12-alpine

# Set the current working directory inside the container
WORKDIR /test

# Copy package.json and package-lock.json files and download deps
COPY package.json package-lock.json ./
RUN npm install

# Copy sources to the working directory
COPY . .

# Set the Node environment
ARG node_env=development
ENV NODE_ENV $node_env

# Run the test suite
RUN npm run test
RUN npm run test:e2e
